import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useLocation } from 'react-router-dom';
import { Send, Download, Monitor, Smartphone, RefreshCw, Code as CodeIcon, Laptop, Layout } from 'lucide-react';
import Button from '../components/Button';
import { generateCodeFromPrompt } from '../services/geminiService';
import { saveProject } from '../services/mockBackend';
import { useAuth } from '../contexts/AuthContext';
import { Template } from '../types';
import JSZip from 'jszip';

const Builder = () => {
  const { user } = useAuth();
  const location = useLocation();
  
  const [creationMode, setCreationMode] = useState<'website' | 'app'>('website');
  const [prompt, setPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedCode, setGeneratedCode] = useState('');
  const [viewMode, setViewMode] = useState<'desktop' | 'mobile'>('desktop');
  const [activeTab, setActiveTab] = useState<'preview' | 'code'>('preview');

  // Handle incoming Template state
  useEffect(() => {
    if (location.state && location.state.template) {
      const template = location.state.template as Template;
      
      // Switch mode based on template category
      setCreationMode(template.category);
      
      // Pre-fill prompt
      setPrompt(template.prompt);
      
      // Load initial code (simulation of "immediate preview")
      setGeneratedCode(template.code);
      
      // Clear state history so refresh doesn't re-trigger (optional but good UX)
      window.history.replaceState({}, document.title);
    }
  }, [location]);

  // Reset view mode when switching creation modes
  useEffect(() => {
    if (creationMode === 'app') {
      setViewMode('mobile');
    } else {
      setViewMode('desktop');
    }
  }, [creationMode]);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setIsGenerating(true);
    // Note: We don't clear generatedCode immediately here if it's a refinement
    // But for a fresh feel, maybe we should. Let's clear it to show progress.
    setGeneratedCode('');

    try {
      // Pass the explicit creationMode (website or app) to the service
      const code = await generateCodeFromPrompt(prompt, creationMode);
      setGeneratedCode(code);

      if (user) {
        saveProject(user.id, prompt.slice(0, 30) + '...', prompt, code, creationMode);
      }

    } catch (error) {
      alert("Generation failed. Please check your connection or try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownload = async () => {
    if (!generatedCode) return;
    
    try {
      const zip = new JSZip();
      
      // Add the main HTML file
      zip.file("index.html", generatedCode);
      
      // Add a README
      zip.file("README.txt", `Generated by Make Your Website in 5 Minutes\n\nPrompt Used:\n${prompt}\n\nInstructions:\n1. Unzip this folder.\n2. Open index.html in any modern web browser.\n3. Enjoy your royal creation.`);

      // Generate the zip file
      const content = await zip.generateAsync({ type: "blob" });
      
      // Trigger download
      const url = URL.createObjectURL(content);
      const a = document.createElement('a');
      a.href = url;
      a.download = `regalis-${creationMode}-project.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Failed to zip file", err);
      alert("Failed to create zip archive.");
    }
  };

  return (
    <div className="h-[calc(100vh-80px)] flex flex-col md:flex-row overflow-hidden bg-black">
      {/* Left Panel: Input & Controls */}
      <div className="w-full md:w-1/3 bg-gray-900 border-r border-gray-800 flex flex-col z-20 shadow-xl relative">
        
        {/* Creation Mode Tabs with Royal Animation */}
        <div className="flex border-b border-gray-800 bg-black relative">
          <button
            onClick={() => setCreationMode('website')}
            className={`flex-1 py-5 text-sm font-serif font-bold tracking-wide uppercase transition-all relative z-10 ${
              creationMode === 'website' ? 'text-royal-gold' : 'text-gray-500 hover:text-gray-300'
            }`}
          >
            <span className="flex items-center justify-center gap-2">
              <Laptop className="w-4 h-4" /> Create Website
            </span>
          </button>
          
          <button
            onClick={() => setCreationMode('app')}
            className={`flex-1 py-5 text-sm font-serif font-bold tracking-wide uppercase transition-all relative z-10 ${
              creationMode === 'app' ? 'text-royal-gold' : 'text-gray-500 hover:text-gray-300'
            }`}
          >
            <span className="flex items-center justify-center gap-2">
              <Smartphone className="w-4 h-4" /> Create Mobile App
            </span>
          </button>

          {/* Golden Slide Indicator */}
          <motion.div 
            className="absolute bottom-0 h-1 bg-royal-gold shadow-[0_0_15px_rgba(212,175,55,0.8)] z-20"
            initial={false}
            animate={{
              width: "50%",
              x: creationMode === 'website' ? "0%" : "100%"
            }}
            transition={{ type: "spring", stiffness: 300, damping: 30 }}
          />
        </div>

        <div className="flex-grow p-6 flex flex-col overflow-y-auto">
          <AnimatePresence mode='wait'>
            <motion.div
              key={creationMode}
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 10 }}
              transition={{ duration: 0.3 }}
              className="flex-grow flex flex-col"
            >
              <h2 className="text-2xl font-serif font-bold text-white mb-2">
                {creationMode === 'website' ? 'Web Platform Vision' : 'Mobile App Concept'}
              </h2>
              <p className="text-gray-400 text-sm mb-6">
                {creationMode === 'website' 
                  ? 'Describe the landing page, portfolio, or e-commerce site you wish to build.' 
                  : 'Describe the mobile app interface, features, and flow you want to prototype.'}
              </p>
              
              <div className="flex-grow mb-6">
                <label className="block text-sm font-medium text-royal-gold mb-2 uppercase tracking-wider text-xs">Prompt</label>
                <textarea
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  className="w-full h-48 bg-black border border-gray-700 rounded-lg p-4 text-white focus:border-royal-gold focus:ring-1 focus:ring-royal-gold outline-none resize-none transition-colors text-sm leading-relaxed placeholder-gray-600 font-mono"
                  placeholder={creationMode === 'website' 
                    ? "E.g., A luxury watch landing page with a black and gold theme, hero section with large typography, and a product gallery grid."
                    : "E.g., A fitness tracking app with a dark mode dashboard showing daily steps, heart rate graph, and quick action buttons."
                  }
                />
              </div>

              <div className="flex gap-2">
                <Button onClick={handleGenerate} isLoading={isGenerating} className="flex-1 w-full">
                  {isGenerating ? 'Generating...' : generatedCode ? 'Regenerate' : 'Generate'} <Send className="w-4 h-4" />
                </Button>
              </div>
            </motion.div>
          </AnimatePresence>

          <div className="pt-8 border-t border-gray-800 mt-6">
            <h3 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-4">Export</h3>
            <Button 
              variant="outline" 
              onClick={handleDownload} 
              disabled={!generatedCode}
              className="w-full"
            >
              <Download className="w-4 h-4" /> Download Source (.zip)
            </Button>
          </div>
        </div>
      </div>

      {/* Right Panel: Preview */}
      <div className="flex-1 bg-neutral-950 relative flex flex-col">
        {/* Toolbar */}
        <div className="h-14 bg-gray-900 border-b border-gray-800 flex items-center justify-between px-4">
           <div className="flex items-center gap-2 bg-black rounded-lg p-1 border border-gray-800">
             <button 
               onClick={() => setActiveTab('preview')}
               className={`px-3 py-1.5 rounded-md text-sm font-medium transition-colors flex items-center gap-2 ${activeTab === 'preview' ? 'bg-royal-gold text-black' : 'text-gray-400 hover:text-white'}`}
             >
               <Monitor className="w-4 h-4" /> Preview
             </button>
             <button 
               onClick={() => setActiveTab('code')}
               className={`px-3 py-1.5 rounded-md text-sm font-medium transition-colors flex items-center gap-2 ${activeTab === 'code' ? 'bg-royal-gold text-black' : 'text-gray-400 hover:text-white'}`}
             >
               <CodeIcon className="w-4 h-4" /> Code
             </button>
           </div>

           {activeTab === 'preview' && creationMode === 'website' && (
              <div className="flex items-center gap-2">
                <button 
                  onClick={() => setViewMode('desktop')}
                  className={`p-2 rounded hover:bg-gray-800 ${viewMode === 'desktop' ? 'text-royal-gold' : 'text-gray-500'}`}
                  title="Desktop View"
                >
                  <Monitor className="w-5 h-5" />
                </button>
                <button 
                  onClick={() => setViewMode('mobile')}
                  className={`p-2 rounded hover:bg-gray-800 ${viewMode === 'mobile' ? 'text-royal-gold' : 'text-gray-500'}`}
                  title="Mobile View"
                >
                  <Smartphone className="w-5 h-5" />
                </button>
              </div>
           )}
           {/* Mobile App Mode always shows mobile icon active */}
           {activeTab === 'preview' && creationMode === 'app' && (
              <div className="flex items-center gap-2 text-royal-gold px-2 text-xs font-medium uppercase tracking-widest">
                <Smartphone className="w-4 h-4 mr-2" /> Mobile App View
              </div>
           )}
        </div>

        {/* Content Area */}
        <div className="flex-grow relative overflow-hidden flex items-center justify-center p-8 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-gray-900 via-black to-black">
          {generatedCode ? (
             activeTab === 'preview' ? (
                <motion.div 
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ duration: 0.5 }}
                  className={`bg-white shadow-[0_0_50px_rgba(0,0,0,0.5)] transition-all duration-500 overflow-hidden relative ${
                    viewMode === 'mobile' 
                      ? 'w-[375px] h-[812px] rounded-[3rem] border-[12px] border-gray-800 ring-1 ring-gray-700' 
                      : 'w-full h-full rounded-lg border border-gray-800'
                  }`}
                >
                  {/* Notch for mobile view */}
                  {viewMode === 'mobile' && (
                    <div className="absolute top-0 left-1/2 -translate-x-1/2 w-32 h-6 bg-gray-800 rounded-b-2xl z-20"></div>
                  )}
                  
                  <iframe 
                    title="Preview"
                    srcDoc={generatedCode}
                    className="w-full h-full border-0 bg-white"
                    sandbox="allow-scripts"
                  />
                </motion.div>
             ) : (
               <div className="w-full h-full bg-[#1e1e1e] rounded-lg overflow-auto p-4 border border-gray-800 text-gray-300 font-mono text-sm shadow-inner">
                 <pre>{generatedCode}</pre>
               </div>
             )
          ) : (
            <div className="text-center text-gray-600">
               <div className="relative inline-block">
                 <RefreshCw className={`w-16 h-16 mx-auto mb-6 ${isGenerating ? 'animate-spin text-royal-gold' : 'text-gray-800'}`} />
                 {!isGenerating && <div className="absolute inset-0 flex items-center justify-center"><Layout className="w-6 h-6 text-gray-700" /></div>}
               </div>
               <h3 className="text-xl font-serif text-gray-500 mb-2">
                 {isGenerating ? 'Designing your masterpiece...' : 'Ready to Create'}
               </h3>
               <p className="text-sm max-w-xs mx-auto text-gray-600">
                 Select a mode, describe your vision, or choose a template to start.
               </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Builder;